# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 09:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='訂票人')),
                ('phone_number', models.CharField(max_length=11, verbose_name='電話號碼')),
                ('ticket_name', models.CharField(default=' ', max_length=30, verbose_name='電影名稱')),
                ('ticket_time', models.DateTimeField(default=datetime.datetime(2018, 1, 21, 17, 4, 45, 258495), verbose_name='購票時間')),
            ],
            options={
                'verbose_name_plural': '訂票人信息',
                'verbose_name': '訂票人信息',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='電影名稱')),
                ('num', models.CharField(default='K100', max_length=10, verbose_name='電影編號')),
                ('time', models.DateTimeField(verbose_name='電影開播時間')),
                ('brief', models.TextField(max_length=300, verbose_name='電影票信息')),
                ('seats', models.IntegerField(default=0, verbose_name='剩餘座位')),
            ],
            options={
                'verbose_name_plural': '電影票信息',
                'verbose_name': '電影票信息',
            },
        ),
    ]
