# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phonenumber', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': '聯絡人資訊',
                'verbose_name': '聯絡人資訊',
            },
        ),
    ]
